  var endpoint= "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22%E5%8F%B0%E5%8C%97%E5%B8%82%22)%20%20and%20u%3D%22c%22&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
  $.getJSON(endpoint,function(data){
	console.log (data) ;
	var currentTemperature = data.query.results.channel.item.condition.temp  ;
  $(".temperature").text(currentTemperature);
  var currentDate = data.query.results.channel.item.forecast[0].date ;
  $(".date").text(currentDate);
  var currentWeather = data.query.results.channel.item.forecast[0].text ;
  $("#nowWeather").text(currentWeather);
  var afterDay1 = data.query.results.channel.item.forecast[1].date ;
  $("#afterDay1").text(afterDay1);
  var afterDay2 = data.query.results.channel.item.forecast[2].date ;
  $("#afterDay2").text(afterDay2);
  var afterDay3 = data.query.results.channel.item.forecast[3].date ;
  $("#afterDay3").text(afterDay3);

  var nextTemp1Low = data.query.results.channel.item.forecast[1].low;
  var nextTemp1High = data.query.results.channel.item.forecast[1].high;
  var nextTemp1 = nextTemp1Low+"-"+nextTemp1High;
  $("#nextTemp1").text(nextTemp1);
  var nextTemp2Low = data.query.results.channel.item.forecast[2].low;
  var nextTemp2High = data.query.results.channel.item.forecast[2].high;
  var nextTemp2 = nextTemp2Low+"-"+nextTemp2High;
  $("#nextTemp2").text(nextTemp2);
  var nextTemp3Low = data.query.results.channel.item.forecast[3].low;
  var nextTemp3High = data.query.results.channel.item.forecast[3].high;
  var nextTemp3 = nextTemp3Low+"-"+nextTemp3High;
  $("#nextTemp3").text(nextTemp3);

  var weatherCode = data.query.results.channel.item.forecast[0].code;
  var weatherCode1 = data.query.results.channel.item.forecast[1].code;
  var weatherCode2 = data.query.results.channel.item.forecast[2].code;
  var weatherCode3 = data.query.results.channel.item.forecast[3].code;
  console.log(weatherCode);
  /*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
 var skycons = new Skycons();

 var icon;
 var icon1;
 var icon2;
 var icon3;

  // you can add a icon to a html canvas. simply supply its element id and the weather you want to show.

if (weatherCode == 32 || weatherCode ==34 || weatherCode ==36){
    icon = Skycons.CLEAR_DAY;
  }else if (weatherCode == 31 || weatherCode ==33){
    icon = Skycons.CLEAR_NIGHT;
  }else if (weatherCode == 30){
    icon = Skycons.PARTLY_CLOUDY_DAY;
  }else if (weatherCode ==29){
    icon = Skycons.PARTLY_CLOUDY_NIGHT;
  }else if (weatherCode == 26 || weatherCode ==27 || weatherCode ==28 || weatherCode ==44){
    icon = Skycons.CLOUDY;
  }else if (weatherCode == 8 || weatherCode ==9 || weatherCode ==10 || weatherCode ==11 || weatherCode ==12){
    icon = Skycons.RAIN;
  }else if (weatherCode == 1 || weatherCode ==2 || weatherCode ==3 || weatherCode ==4 || weatherCode ==37 || weatherCode ==38 || weatherCode ==39 || weatherCode ==40 || weatherCode ==45 || weatherCode ==47){
    icon = Skycons.SLEET;
  }else if (weatherCode == 5 || weatherCode ==6 || weatherCode ==7 || weatherCode ==13 || weatherCode ==14 || weatherCode ==15 || weatherCode ==16 || weatherCode ==17 || weatherCode ==18 || weatherCode ==25 || weatherCode ==35 || weatherCode ==41 || weatherCode ==42 || weatherCode ==43 || weatherCode ==46){
    icon = Skycons.SNOW;
  }else if (weatherCode == 0 || weatherCode ==23 || weatherCode ==24){
    icon = Skycons.WIND;
  }else if (weatherCode == 19 || weatherCode ==20 || weatherCode ==21 || weatherCode ==22){
    icon = Skycons.FOG;
  }
    if (weatherCode1 == 32 || weatherCode1 ==34 || weatherCode1 ==36){
    icon1 = Skycons.CLEAR_DAY;
  }else if (weatherCode1 == 31 || weatherCode1 ==33){
    icon1 = Skycons.CLEAR_NIGHT;
  }else if (weatherCode1 == 30){
    icon1 = Skycons.PARTLY_CLOUDY_DAY;
  }else if (weatherCode1 == 29){
    icon1 = Skycons.PARTLY_CLOUDY_NIGHT;
  }else if (weatherCode1 == 26 || weatherCode1 ==27 || weatherCode1 ==28 || weatherCode1 ==44){
    icon1 = Skycons.CLOUDY;
  }else if (weatherCode1 == 8 || weatherCode1 ==9 || weatherCode1 ==10 || weatherCode1 ==11 || weatherCode1 ==12){
    icon1 = Skycons.RAIN;
  }else if (weatherCode1 == 1 || weatherCode1 ==2 || weatherCode1 ==3 || weatherCode1 ==4 || weatherCode1 ==37 || weatherCode1 ==38 || weatherCode1 ==39 || weatherCode1 ==40 || weatherCode1 ==45 || weatherCode1 ==47){
    icon1 = Skycons.SLEET;
  }else if (weatherCode1 == 5 || weatherCode1 ==6 || weatherCode1 ==7 || weatherCode1 ==13 || weatherCode1 ==14 || weatherCode1 ==15 || weatherCode1 ==16 || weatherCode1 ==17 || weatherCode1 ==18 || weatherCode1==25 || weatherCode1 ==35 || weatherCode1 ==41 || weatherCode1 ==42 || weatherCode1 ==43 || weatherCode1 ==46){
    icon1 = Skycons.SNOW;
  }else if (weatherCode1 == 0 || weatherCode1 ==23 || weatherCode1 ==24){
    icon1 = Skycons.WIND;
  }else if (weatherCode1 == 19 || weatherCode1 ==20 || weatherCode1 ==21 || weatherCode1 ==22){
    icon1 = Skycons.FOG;
  }
    if (weatherCode2 == 32 || weatherCode2 ==34 || weatherCode2 ==36){
    icon2 = Skycons.CLEAR_DAY;
  }else if (weatherCode2 == 31 || weatherCode2 ==33){
    icon2 = Skycons.CLEAR_NIGHT;
  }else if (weatherCode2 == 30){
    icon2 = Skycons.PARTLY_CLOUDY_DAY;
  }else if (weatherCode2 == 29){
    icon2 = Skycons.PARTLY_CLOUDY_NIGHT;
  }else if (weatherCode2 == 26 || weatherCode2 ==27 || weatherCode2 ==28 || weatherCode2 ==44){
    icon2 = Skycons.CLOUDY;
  }else if (weatherCode2 == 8 ||weatherCode2 == 9 || weatherCode2 ==10 || weatherCode2 ==11 || weatherCode2 ==12){
    icon2 = Skycons.RAIN;
  }else if (weatherCode2 == 1 || weatherCode2 ==2 || weatherCode2 ==3 || weatherCode2 ==4 || weatherCode2 ==37 || weatherCode2 ==38 || weatherCode2 ==39 || weatherCode2 ==40 || weatherCode2 ==45 || weatherCode2 ==47){
    icon2 = Skycons.SLEET;
  }else if (weatherCode2 == 5 || weatherCode2 ==6 || weatherCode2 ==7 || weatherCode2 ==13 || weatherCode2 ==14 || weatherCode2 ==15 || weatherCode2 ==16 || weatherCode2 ==17 || weatherCode2 ==18 || weatherCode2 ==25 || weatherCode2 ==35 || weatherCode2 ==41 || weatherCode2 ==42 || weatherCode2 ==43 || weatherCode2 ==46){
    icon2 = Skycons.SNOW;
  }else if (weatherCode2 == 0 || weatherCode2 ==23 || weatherCode2 ==24){
    icon2 = Skycons.WIND;
  }else if (weatherCode2 == 19 || weatherCode2 ==20 || weatherCode2 ==21 || weatherCode2 ==22){
    icon2 = Skycons.FOG;
  }
    if (weatherCode3 == 32 || weatherCode3 ==34 || weatherCode3 ==36){
    icon3 = Skycons.CLEAR_DAY;
  }else if (weatherCode3 == 31 || weatherCode3 ==33){
    icon3 = Skycons.CLEAR_NIGHT;
  }else if (weatherCode3 == 30){
    icon3 = Skycons.PARTLY_CLOUDY_DAY;
  }else if (weatherCode3 == 29){
    icon3 = Skycons.PARTLY_CLOUDY_NIGHT;
  }else if (weatherCode3 == 26 || weatherCode3 ==27 || weatherCode3 ==28 || weatherCode3 ==44){
    icon3 = Skycons.CLOUDY;
  }else if (weatherCode3 == 8 || weatherCode3 ==9 || weatherCode3 ==10 || weatherCode3 ==11 || weatherCode3 ==12){
    icon3 = Skycons.RAIN;
  }else if (weatherCode3 == 1 || weatherCode3 ==2 || weatherCode3 ==3 || weatherCode3 ==4 || weatherCode3 ==37 || weatherCode3 ==38 || weatherCode3 ==39 || weatherCode3 ==40 || weatherCode3 ==45 || weatherCode3 ==47){
    icon3 = Skycons.SLEET;
  }else if (weatherCode3 == 5 || weatherCode3 ==6 || weatherCode3 ==7 || weatherCode3 ==13 || weatherCode3 ==14 || weatherCode3 ==15 || weatherCode3 ==16 || weatherCode3 ==17 || weatherCode3 ==18 || weatherCode3 ==25 || weatherCode3 ==35 || weatherCode3 ==41 || weatherCode3 ==42 || weatherCode3 ==43 || weatherCode3 ==46){
    icon3 = Skycons.SNOW;
  }else if (weatherCode3 == 0 || weatherCode3 ==23 || weatherCode3 ==24){
    icon3 = Skycons.WIND;
  }else if (weatherCode3 == 19 || weatherCode3 ==20 || weatherCode3 ==21 || weatherCode3 ==22){
    icon3 = Skycons.FOG;
  }

  skycons.add("today", icon);
  skycons.add("day1", icon1);
  skycons.add("day2", icon2);
  skycons.add("day3", icon3);
  // start all icons animation!
  skycons.play();

  // update a icon on  canvas by its id
  //skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);

/*
Get value from Bootstrap dropdown menu
*/


 });


  $('#dropdown li').on('click', function(){
   // alert($(this).text());
    var index = $(this).text();
   console.log(index);
   $("button").text(index);

   
   
   if (index == "台北市"){
     endpoint = "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22%E5%8F%B0%E5%8C%97%E5%B8%82%22)%20%20and%20u%3D%22c%22&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
   }else if(index == "新北市"){
     endpoint="https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22%E6%96%B0%E5%8C%97%E5%B8%82%22%20%20)and%20u%3D%22c%22&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
   }else if(index == "連江縣"){
     endpoint="https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22%E9%A6%AC%E7%A5%96%22%20%20)and%20u%3D%22c%22&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
   }else if(index =="台中市"){
     endpoint="https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22%E5%8F%B0%E4%B8%AD%E5%B8%82%22%20%20)and%20u%3D%22c%22&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
   }else if(index =="台南市"){
     endpoint="https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22%E5%8F%B0%E5%8D%97%E5%B8%82%22%20%20)and%20u%3D%22c%22&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
   }else if(index =="高雄市"){
     endpoint="https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22%E9%AB%98%E9%9B%84%E5%B8%82%22%20%20)and%20u%3D%22c%22&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
   }else if(index =="基隆市"){
     endpoint="https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22%E5%9F%BA%E9%9A%86%E5%B8%82%22%20%20)and%20u%3D%22c%22&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
   }else if(index =="桃園市"){
     endpoint="https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22%E6%A1%83%E5%9C%92%E5%B8%82%22%20%20)and%20u%3D%22c%22&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
   }else if(index =="新竹市"){
     endpoint="https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22%E6%96%B0%E7%AB%B9%E5%B8%82%22%20%20)and%20u%3D%22c%22&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
   }else if(index =="新竹縣"){
     endpoint="https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22%E6%96%B0%E7%AB%B9%E7%B8%A3%22%20%20)and%20u%3D%22c%22&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
   }else if(index =="苗栗縣"){
     endpoint="https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22%E8%8B%97%E6%A0%97%E7%B8%A3%22%20%20)and%20u%3D%22c%22&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
   }else if(index =="彰化縣"){
     endpoint="https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22%E5%BD%B0%E5%8C%96%E7%B8%A3%22%20%20)and%20u%3D%22c%22&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
   }else if(index =="南投縣"){
     endpoint="https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22%E5%8D%97%E6%8A%95%E7%B8%A3%22%20%20)and%20u%3D%22c%22&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
   }else if(index =="雲林縣"){
     endpoint="https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22%E9%9B%B2%E6%9E%97%E7%B8%A3%22%20%20)and%20u%3D%22c%22&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
   }else if(index =="嘉義市"){
     endpoint="https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22%E5%98%89%E7%BE%A9%E5%B8%82%22%20%20)and%20u%3D%22c%22&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
   }else if(index =="嘉義縣"){
     endpoint="https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22%E5%98%89%E7%BE%A9%E7%B8%A3%22%20%20)and%20u%3D%22c%22&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
   }else if(index =="屏東縣"){
     endpoint="https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22%E5%B1%8F%E6%9D%B1%E7%B8%A3%22%20%20)and%20u%3D%22c%22&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
   }else if(index =="宜蘭縣"){
     endpoint="https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22%E5%AE%9C%E8%98%AD%E7%B8%A3%22%20%20)and%20u%3D%22c%22&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
   }else if(index =="花蓮縣"){
     endpoint="https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22%E8%8A%B1%E8%93%AE%E7%B8%A3%22%20%20)and%20u%3D%22c%22&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
   }else if(index =="台東縣"){
     endpoint="https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22%E5%8F%B0%E6%9D%B1%E7%B8%A3%22%20%20)and%20u%3D%22c%22&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
   }else if(index =="澎湖縣"){
     endpoint="https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22%E6%BE%8E%E6%B9%96%E7%B8%A3%22%20%20)and%20u%3D%22c%22&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
   }else if(index =="金門縣"){
     endpoint="https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22%E9%87%91%E9%96%80%E7%B8%A3%22%20%20)and%20u%3D%22c%22&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
   }
   

  
  $.getJSON(endpoint,function(data){
	console.log (data) ;
	var currentTemperature = data.query.results.channel.item.condition.temp  ;
  $(".temperature").text(currentTemperature);
  var currentDate = data.query.results.channel.item.forecast[0].date ;
  $(".date").text(currentDate);
  var currentWeather = data.query.results.channel.item.forecast[0].text ;
  $("#nowWeather").text(currentWeather);
  var afterDay1 = data.query.results.channel.item.forecast[1].date ;
  $("#afterDay1").text(afterDay1);
  var afterDay2 = data.query.results.channel.item.forecast[2].date ;
  $("#afterDay2").text(afterDay2);
  var afterDay3 = data.query.results.channel.item.forecast[3].date ;
  $("#afterDay3").text(afterDay3);

  var nextTemp1Low = data.query.results.channel.item.forecast[1].low;
  var nextTemp1High = data.query.results.channel.item.forecast[1].high;
  var nextTemp1 = nextTemp1Low+"-"+nextTemp1High;
  $("#nextTemp1").text(nextTemp1);
  var nextTemp2Low = data.query.results.channel.item.forecast[2].low;
  var nextTemp2High = data.query.results.channel.item.forecast[2].high;
  var nextTemp2 = nextTemp2Low+"-"+nextTemp2High;
  $("#nextTemp2").text(nextTemp2);
  var nextTemp3Low = data.query.results.channel.item.forecast[3].low;
  var nextTemp3High = data.query.results.channel.item.forecast[3].high;
  var nextTemp3 = nextTemp3Low+"-"+nextTemp3High;
  $("#nextTemp3").text(nextTemp3);

  var weatherCode = data.query.results.channel.item.forecast[0].code;
  var weatherCode1 = data.query.results.channel.item.forecast[1].code;
  var weatherCode2 = data.query.results.channel.item.forecast[2].code;
  var weatherCode3 = data.query.results.channel.item.forecast[3].code;
  console.log(weatherCode);
  /*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
 var skycons = new Skycons();

 var icon;
 var icon1;
 var icon2;
 var icon3;

  // you can add a icon to a html canvas. simply supply its element id and the weather you want to show.

if (weatherCode == 32 || weatherCode ==34 || weatherCode ==36){
    icon = Skycons.CLEAR_DAY;
  }else if (weatherCode == 31 || weatherCode ==33){
    icon = Skycons.CLEAR_NIGHT;
  }else if (weatherCode == 30){
    icon = Skycons.PARTLY_CLOUDY_DAY;
  }else if (weatherCode ==29){
    icon = Skycons.PARTLY_CLOUDY_NIGHT;
  }else if (weatherCode == 26 || weatherCode ==27 || weatherCode ==28 || weatherCode ==44){
    icon = Skycons.CLOUDY;
  }else if (weatherCode == 8 || weatherCode ==9 || weatherCode ==10 || weatherCode ==11 || weatherCode ==12){
    icon = Skycons.RAIN;
  }else if (weatherCode == 1 || weatherCode ==2 || weatherCode ==3 || weatherCode ==4 || weatherCode ==37 || weatherCode ==38 || weatherCode ==39 || weatherCode ==40 || weatherCode ==45 || weatherCode ==47){
    icon = Skycons.SLEET;
  }else if (weatherCode == 5 || weatherCode ==6 || weatherCode ==7 || weatherCode ==13 || weatherCode ==14 || weatherCode ==15 || weatherCode ==16 || weatherCode ==17 || weatherCode ==18 || weatherCode ==25 || weatherCode ==35 || weatherCode ==41 || weatherCode ==42 || weatherCode ==43 || weatherCode ==46){
    icon = Skycons.SNOW;
  }else if (weatherCode == 0 || weatherCode ==23 || weatherCode ==24){
    icon = Skycons.WIND;
  }else if (weatherCode == 19 || weatherCode ==20 || weatherCode ==21 || weatherCode ==22){
    icon = Skycons.FOG;
  }
    if (weatherCode1 == 32 || weatherCode1 ==34 || weatherCode1 ==36){
    icon1 = Skycons.CLEAR_DAY;
  }else if (weatherCode1 == 31 || weatherCode1 ==33){
    icon1 = Skycons.CLEAR_NIGHT;
  }else if (weatherCode1 == 30){
    icon1 = Skycons.PARTLY_CLOUDY_DAY;
  }else if (weatherCode1 == 29){
    icon1 = Skycons.PARTLY_CLOUDY_NIGHT;
  }else if (weatherCode1 == 26 || weatherCode1 ==27 || weatherCode1 ==28 || weatherCode1 ==44){
    icon1 = Skycons.CLOUDY;
  }else if (weatherCode1 == 8 || weatherCode1 ==9 || weatherCode1 ==10 || weatherCode1 ==11 || weatherCode1 ==12){
    icon1 = Skycons.RAIN;
  }else if (weatherCode1 == 1 || weatherCode1 ==2 || weatherCode1 ==3 || weatherCode1 ==4 || weatherCode1 ==37 || weatherCode1 ==38 || weatherCode1 ==39 || weatherCode1 ==40 || weatherCode1 ==45 || weatherCode1 ==47){
    icon1 = Skycons.SLEET;
  }else if (weatherCode1 == 5 || weatherCode1 ==6 || weatherCode1 ==7 || weatherCode1 ==13 || weatherCode1 ==14 || weatherCode1 ==15 || weatherCode1 ==16 || weatherCode1 ==17 || weatherCode1 ==18 || weatherCode1==25 || weatherCode1 ==35 || weatherCode1 ==41 || weatherCode1 ==42 || weatherCode1 ==43 || weatherCode1 ==46){
    icon1 = Skycons.SNOW;
  }else if (weatherCode1 == 0 || weatherCode1 ==23 || weatherCode1 ==24){
    icon1 = Skycons.WIND;
  }else if (weatherCode1 == 19 || weatherCode1 ==20 || weatherCode1 ==21 || weatherCode1 ==22){
    icon1 = Skycons.FOG;
  }
    if (weatherCode2 == 32 || weatherCode2 ==34 || weatherCode2 ==36){
    icon2 = Skycons.CLEAR_DAY;
  }else if (weatherCode2 == 31 || weatherCode2 ==33){
    icon2 = Skycons.CLEAR_NIGHT;
  }else if (weatherCode2 == 30){
    icon2 = Skycons.PARTLY_CLOUDY_DAY;
  }else if (weatherCode2 == 29){
    icon2 = Skycons.PARTLY_CLOUDY_NIGHT;
  }else if (weatherCode2 == 26 || weatherCode2 ==27 || weatherCode2 ==28 || weatherCode2 ==44){
    icon2 = Skycons.CLOUDY;
  }else if (weatherCode2 == 8 ||weatherCode2 == 9 || weatherCode2 ==10 || weatherCode2 ==11 || weatherCode2 ==12){
    icon2 = Skycons.RAIN;
  }else if (weatherCode2 == 1 || weatherCode2 ==2 || weatherCode2 ==3 || weatherCode2 ==4 || weatherCode2 ==37 || weatherCode2 ==38 || weatherCode2 ==39 || weatherCode2 ==40 || weatherCode2 ==45 || weatherCode2 ==47){
    icon2 = Skycons.SLEET;
  }else if (weatherCode2 == 5 || weatherCode2 ==6 || weatherCode2 ==7 || weatherCode2 ==13 || weatherCode2 ==14 || weatherCode2 ==15 || weatherCode2 ==16 || weatherCode2 ==17 || weatherCode2 ==18 || weatherCode2 ==25 || weatherCode2 ==35 || weatherCode2 ==41 || weatherCode2 ==42 || weatherCode2 ==43 || weatherCode2 ==46){
    icon2 = Skycons.SNOW;
  }else if (weatherCode2 == 0 || weatherCode2 ==23 || weatherCode2 ==24){
    icon2 = Skycons.WIND;
  }else if (weatherCode2 == 19 || weatherCode2 ==20 || weatherCode2 ==21 || weatherCode2 ==22){
    icon2 = Skycons.FOG;
  }
    if (weatherCode3 == 32 || weatherCode3 ==34 || weatherCode3 ==36){
    icon3 = Skycons.CLEAR_DAY;
  }else if (weatherCode3 == 31 || weatherCode3 ==33){
    icon3 = Skycons.CLEAR_NIGHT;
  }else if (weatherCode3 == 30){
    icon3 = Skycons.PARTLY_CLOUDY_DAY;
  }else if (weatherCode3 == 29){
    icon3 = Skycons.PARTLY_CLOUDY_NIGHT;
  }else if (weatherCode3 == 26 || weatherCode3 ==27 || weatherCode3 ==28 || weatherCode3 ==44){
    icon3 = Skycons.CLOUDY;
  }else if (weatherCode3 == 8 || weatherCode3 ==9 || weatherCode3 ==10 || weatherCode3 ==11 || weatherCode3 ==12){
    icon3 = Skycons.RAIN;
  }else if (weatherCode3 == 1 || weatherCode3 ==2 || weatherCode3 ==3 || weatherCode3 ==4 || weatherCode3 ==37 || weatherCode3 ==38 || weatherCode3 ==39 || weatherCode3 ==40 || weatherCode3 ==45 || weatherCode3 ==47){
    icon3 = Skycons.SLEET;
  }else if (weatherCode3 == 5 || weatherCode3 ==6 || weatherCode3 ==7 || weatherCode3 ==13 || weatherCode3 ==14 || weatherCode3 ==15 || weatherCode3 ==16 || weatherCode3 ==17 || weatherCode3 ==18 || weatherCode3 ==25 || weatherCode3 ==35 || weatherCode3 ==41 || weatherCode3 ==42 || weatherCode3 ==43 || weatherCode3 ==46){
    icon3 = Skycons.SNOW;
  }else if (weatherCode3 == 0 || weatherCode3 ==23 || weatherCode3 ==24){
    icon3 = Skycons.WIND;
  }else if (weatherCode3 == 19 || weatherCode3 ==20 || weatherCode3 ==21 || weatherCode3 ==22){
    icon3 = Skycons.FOG;
  }

  skycons.add("today", icon);
  skycons.add("day1", icon1);
  skycons.add("day2", icon2);
  skycons.add("day3", icon3);
  // start all icons animation!
  skycons.play();

  // update a icon on  canvas by its id
  //skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);

/*
Get value from Bootstrap dropdown menu
*/


 });
})


